### ISSUE TITLE
design discussion 1: slicing should work same as in D's mir N-D tensor library (and same as numpy)

### ISSUE THREAD

**Issue by timotheecour** [mratsim/Arraymancer#262]
/cc @mratsim  I think Arraymancer could borrow a number of design ideas from `mir`,  @9il's excellent  N-dimensional tensor library (see [1] [2] [3] [4] ):

* in `mir`, a N-D tensor is just a view over some data, and is not concerned with memory management of this data [5]. This allows copy-free operations on existing buffers (eg from C, etc), and simplifies the design a lot
* it even allows using tensor views on arbitrary ranges (not necessarily backed by an in memory buffer, eg D's `iota`, eg see [here](http://docs.algorithm.dlang.io/latest/mir_ndslice_topology.html#.iota which is implicit)
* `mir` uses a better approach to slicing: dimension is reduced when a slice dimension is a scalar instead of a range; this makes API's more interoperable (eg: no distinction made bw a 1D slice of a 3D tensor, 2D tensor, or 1D tensor)
* errors is slicing dimension mismatch cause compile time errors instead of runtime errors

NOTE: mir's behavior actually matches python's numpy behavior in terms of how slicing works, see [6]

```d
/+dub.sdl:
dependency "mir-algorithm" version="~>1.1.1"
+/

/+
NOTE: run with: `dub filename.d`
+/

import std.stdio;
import mir.ndslice;
import std.conv:to;

void test1() {
    auto matrix = slice!double(3, 4);
    static assert(matrix.shape.length == 2);

    matrix[] = 0;
    matrix.diagonal[] = 1;

    assert(matrix.shape == [3, 4]);
    {
      auto matrix2D = matrix[1..$, 0..$-1];
      static assert(matrix2D.shape.length == 2);
      assert(matrix2D.shape == [2, 3]);
    }

    {
      // dimension is reduced when slice contains a scalar instead of a range:
      auto matrix1D = matrix[1, 1..$];
      static assert(matrix1D.shape.length == 1);
      assert(matrix1D.shape == [3]);
    }

    {
      // likewise with arguments flipped
      // NOTE: works with arbitrary number of dimensions and does the right thing
      auto matrix1D = matrix[1..$, $-1];
      static assert(matrix1D.shape.length == 1);
      assert(matrix1D.shape == [2]);
    }

    {
      // when all arguments are scalars, downgrades to a scalar (ie, 0 dimensions)
      auto matrix0D = matrix[0, 0];
      assert(matrix0D == 1.0);
    }

    {
      // when only a subset of dimensions are specified, sub tensor is returned:
      auto matrix1D = matrix[2];
      static assert(matrix1D.shape.length == 1);
      assert(matrix1D.shape == [4]);
      matrix1D[3] = 6;
      assert(matrix[2, 3] == 6); // D & C index order
    }

    matrix.writeln;
    assert(matrix.to!string == "[[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 6]]");
}

void test2() {
    // can create a N-D tensor from an existing buffer (just a view over buffer)
    auto a=[0,1,2,3];
    auto matrix = a.sliced(2, 2);
    matrix[0][] = 100;
    assert(matrix.to!string == "[[100, 100], [2, 3]]");
    assert(a == [100, 100, 2, 3]);
}

void test3() {
    // can create a N-D tensor from an arbitrary range, not necessarily backed by an in-memory buffer
    auto a=iota(6);
    auto matrix = a.sliced(2, 3);
    assert(matrix.to!string == "[[0, 1, 2], [3, 4, 5]]");
}

void main(){
  test1();
  test2();
  test3();
}
```

see snippet below using arraymancer, when i denote by BUG things that may not currently be considered as bugs but which should be IMO:
```nim
import arraymancer

import timn/util

proc test()=
  var d = [[1, 2, 3], [4, 5, 6]].toTensor()
  # BUG: prints an extra "\n"
  echo d

  when false:
    #BUG: runtime error instead of CT error
    echo d[0]

  echo "hi"
  echo d[0,0]
  d[0,0]=10
  echo d

  # BUG: should throw out of bound error
  echo d[0..2, 0]

  echo d[0,0..2]

  # BUG: d[0, 0..2] should reduce rank of tensor, as in Mir
  var temp = d[0, 0..2]
  echo temp
  echo temp[0, 0]
  when true:
    for i in 0..<temp.shape[1]:
      temp[0, i] = 200
  echo temp
  echo d

  # echo "foo"
  # echo2 "bar"

proc test2()=
  var d0 = [1, 2, 3]
  var d = d0.toTensor()
  echo2 d0
  echo2 d
  d0[0] = 10
  echo2 d0
  # BUG: d0 should be affected
  echo2 d

test()
test2()
```

[1] http://docs.algorithm.dlang.io/latest/mir_ndslice.html
[2] https://github.com/libmir/mir-algorithm
[3] blog: http://blog.mir.dlang.io/
[4] http://blog.mir.dlang.io/glas/benchmark/openblas/2016/09/23/glas-gemm-benchmark.html shows: Mir GLAS is faster than OpenBLAS and Eigen
[5] a slice is not directly concerned with memory management but its easy to delegate this task to wrapper functions, as done in mir library so that, for eg, `auto matrix = slice!double(3, 4);` works

[ 6] numpy example show slicing matches mir but not arraymancer:
```py
import numpy as np
a=np.zeros([2,3,4])
a[0, 1:2, 0:3].shape #(1, 3)
a[0:0, 1:2, 0:3].shape #(0, 1, 3)
a[0, 1:2].shape #(1, 4)
```

**Comment by timotheecour** [comment]
here's a strong performance argument in favor of compile time tensor rank (part of tensor type):
composing a pipeline of operations becomes optimized away by compiler optimizations, as if there was a single such operation. This would not be possible with runtime rank.

for proof, see this crazy extreme example, that @9il had done [source code](https://gist.github.com/9il/bc7966823d96557c566c); he successfully convinced me that compiler optimizations will optimize away a pipeline of composition:
```d
void crazy_test(Slice!(4, double*) slice)
{
    slice
        .transposed!(3, 2)
        .pack!(2)
        .evertPack
        .unpack
        .swapped!(1, 3)
        .strided(2, 3)
        .reversed!(0)
        .everted
        [8, 0..$, 7, 2..$] *= 10.0;
}
```

see generated machine code here: https://gist.github.com/9il/47aea1621a9fba609869 , showing how small generated code for `crazy_test` is: __D3app10crazy_testFS3std12experimental7ndslice5slice17__T5SliceVmi4TPdZ5SliceZv

**Comment by mratsim** [comment]
Sorry I didn't have the time to reply before:

1. Here there is an ergonomic tradeoff, working on existing buffer would allow easy FFI (with Numpy especially) but would force the user to carry the metadata and manage the lifetime of the buffer. I do plan to have a no-copy, very low-level API, that only uses pre-allocated buffers so that's it's possible to reuse buffers and avoid GC but I think it's best to wait for destructors, see https://github.com/mratsim/Arraymancer/issues/175.

2. Agree

3. This is similar to Numpy and I intentionally don't replicate this behaviour, you can use `d.at(0, 0..2)` instead. This trips people:
  * https://stackoverflow.com/questions/24441326/dealing-with-dimension-collapse-in-python-arrays
  * https://stackoverflow.com/questions/3551242/numpy-index-slice-without-losing-dimension-information
  This "feature" makes it that a lot of Numpy library code is plagued by `np.atleast_1d` and `np.atleast_2d` as the `keepdims=true` option for slicing was late to the show. I prefer not forcing my assumption on users and I think `at` is ergonomic enough though hard to discover.

## Having the rank part of the tensor type

This one deserve a whole section

I would love to have tensor rank be a static[int] and part of the type but it will not work.

1. Reading from .npy file would require `let x = read_npy("path/to/file", 2)` assuming it's rank 2. Instead I would have to use a template that switches on the dynamic shape read and then call read_npy with the proper static parameter. And any new serialization format supported would require that kind of scheme.

2. As shape depends on runtime data, `squeeze` depends on runtime data. You cannot pass this test with compile-time rank: https://github.com/mratsim/Arraymancer/blob/a2db9b38729bb2b0111e56412e750eb25b677920/tests/tensor/test_shapeshifting.nim#L94-L99

### Performance:

I'm not too sure of what is happening with the shape/strides in the crazy_test example but I did benchmark a lot various iteration schemes, see #164. The key point is to make sure the shape, the strides and length are stored on the stack ideally in as few cache lines as possible, which I'm doing by having Arraymancer support rank 7 at most (so 7 int + 1 int for rank) so shape + strides take exactly 2 cache lines on x86_64.

Having the rank be part of the type means that I could use a single cache line for tensors of up to rank 4, I could use int32 for that as well, maybe something to test but due to hardware prefetching and the cost of zero-extension I think there is not much to get there.

Regarding iteration scheme I tried to find Mir equivalent to this scheme (note this was before i used stack arrays everywhere):

```Nim
template strided_iteration[T](t: Tensor[T], strider: IterKind): untyped =
  ## Iterate over a Tensor, displaying data as in C order, whatever the strides.

  ## Iterator init
  var coord = newSeq[int](t.rank) # Coordinates in the n-dimentional space
  var backstrides: seq[int] = @[] # Offset between end of dimension and beginning
  for i,j in zip(t.strides,t.shape):
    backstrides.add(i*(j-1))

  var iter_pos = t.offset

  ## Iterator loop
  for i in 0 ..< t.shape.product:

    ## Templating the return value
    when strider == IterKind.Values: yield t.data[iter_pos]
    elif strider == IterKind.Coord_Values: yield (coord, t.data[iter_pos])
    elif strider == IterKind.MemOffset: yield iter_pos
    elif strider == IterKind.MemOffset_Values: yield (iter_pos, t.data[iter_pos])

    ## Computing the next position
    for k in countdown(t.rank - 1,0):
      if coord[k] < t.shape[k]-1:
        coord[k] += 1
        iter_pos += t.strides[k]
        break
      else:
        coord[k] = 0
        iter_pos -= backstrides[k]
```

in https://github.com/libmir/mir-algorithm/blob/83609c917020a84d21ea7dde0cd3eba064a21e9b/source/mir/ndslice/iterator.d but I couldn't find it. However as only rank is static and shape is dynamic I am pretty sure Mir also implements "tuple iteration" (from TRIOT #164 taxonomy of iteration scheme) so there shouldn't be any performance difference here even with unrolling as there is a costly inner "if statement" and no vectorization opportunity.

**Comment by mratsim** [comment]
After rethinking about 1, I'm thinking of changing the CpuStorage from:

```Nim
type
  CpuStorage* {.shallow.} [T] = object
    ## Opaque data storage for Tensors
    ## Currently implemented as a seq with reference semantics (shallow copy on assignment).
    ## It may change in the future for a custom memory managed and 64 bit aligned solution.
    ##
    ## Warning ⚠:
    ##   Do not use Fdata directly, direct access will be removed in 0.4.0.

    # `Fdata` will be transformed into an opaque type once `unsafeToTensorReshape` is removed.
    Fdata*: seq[T]
```

to

```Nim
type
  CpuStorage*[T] = object
    Fdata*: ptr UncheckedArray[T] # data aligned to 64-bit offset
    when compileOption("boundChecks"):
      len: int # For bound checking check in debug mode
    memalloc: ptr T # ptr to memory allocated
    memowner: bool # if true, deallocated memory when object is destroyed
```

This would allow easier interop with external libraries, especially no-copy Numpy integration (cc @lemonboy), memmapped data processing and might be needed for streaming video processing as well.

The memowner field will be checked by the future destructors. If it is set, memory will be deallocated and not otherwise. This enables both ergonomic usage for normal user and advanced features for libraries and performance purposes.

Also this would also allow custom allocators (for caching/reusing buffers) and control alignment #102.

**Comment by LemonBoy** [comment]
I'm not sure that `ptr T` is the right type. For the numpy case (arraymancer -> np) the memory blob (that's casted into `Fdata`) belongs to a `PyObject` object so `memalloc` should be just a `pointer` IMO.

**Comment by timotheecour** [comment]
also worth considering: there's also `Any`, (see typeinfo.nim) which wraps any nim value (by its address) into a Any object that contains the value's typeinfo along with its address
the best choice should prioritize speed first, expressivity second

**Comment by mratsim** [comment]
As mentioned on IRC/Gitter I've started working on [Laser](https://github.com/numforge/laser) to address point 1 and 2:

> * in mir, a N-D tensor is just a view over some data, and is not concerned with memory management of this data [5]. This allows copy-free operations on existing buffers (eg from C, etc), and simplifies the design a lot
> * it even allows using tensor views on arbitrary ranges (not necessarily backed by an in memory buffer, eg D's iota, eg see [here](http://docs.algorithm.dlang.io/latest/mir_ndslice_topology.html#.iota which is implicit)

and move Arraymancer backend over.

I've carefully benchmarked [several iteration schemes](https://github.com/numforge/laser/blob/master/benchmarks/loop_iteration/iter_bench.nim) and it should be the fastest and most compact you can get while supporting strided iteration being variadic and parallel through OpenMP, the syntax is a simple:

```Nim
forEach o in output, x in a, y in b, z in c:
      o = x + y - sin z
```

Unfortunately I can't find the strided iterator in Mir either in [iterator](https://github.com/libmir/mir-algorithm/blob/devel/source/mir/ndslice/iterator.d) or [topology](https://github.com/libmir/mir-algorithm/blob/devel/source/mir/ndslice/topology.d) to compare implementation.

Regarding the [tensor type](https://github.com/numforge/laser/blob/e9bbb1055517c6e76649b67737d7b8807af22eb2/laser/tensor/datatypes.nim) it will be a simple:
```Nim
type
  RawImmutableView*[T] = distinct ptr UncheckedArray[T]
  RawMutableView*[T] = distinct ptr UncheckedArray[T]

  Metadata* = DynamicStackArray[int]

  Tensor*[T] = object                    # Total stack: 128 bytes = 2 cache-lines
    shape*: Metadata                     # 56 bytes
    strides*: Metadata                   # 56 bytes
    offset*: int                         # 8 bytes
    storage*: CpuStorage[T]              # 8 bytes

  CpuStorage*{.shallow.}[T] = ref object # Total heap: 25 bytes = 1 cache-line
    when supportsCopyMem(T):
      raw_data*: ptr UncheckedArray[T]   # 8 bytes
      memalloc*: pointer                 # 8 bytes
      memowner*: bool                    # 1 byte
    else: # Tensors of strings, other ref types or non-trivial destructors
      raw_data*: seq[T]                  # 8 bytes (16 for seq v2 backed by destructors?)
```

Closing as the first 2 points are being addressed, further discussion should be in [laser repo](https://github.com/numforge/laser).

3rd point has the `at` alternative.

The last point as no solution that would work with `squeeze` which is used a lot and is not ergonomic for initialization (doesn't work with varargs for example).
