### ISSUE TITLE
Linear system solution (LU)

### ISSUE THREAD

**Issue by auxym** [mratsim/Arraymancer#389]
I did some digging around and it seems LU decomposition was recently added to Arraymancer (#382).

*Somewhat sidetracking: any reason why the LAPACK LU result is duplicated in two tensors in `lu_permuted`? It seems like an easy memory optimization to avoid this duplication  (each matrix is half zeros). Scipy's wrapper to `DGETRF`, `scipy.linalg.lu_factor`, returns a single array lu as the wrapped function does.*

Ok, back to the main focus: solving a linear system of equations `AX = B` is a very common thing to do, and LU factorization is a classic, widely applicable and decently efficient way to do it. We could wrap `DGETRS`, except:

1. `DGETRS` wants to do the permutation which is already done in arraymancer's `lu_permuted` wrapper.

2. `DGETRS` expects a single LU matrix as returned by `DGETRF`.

Proposals:

1. Merge `L` and `U` back into a single matrix (`L + U`) and pass a no-op array `IPIV` to `DGETRS`. Easiest but least efficient option.

2. Directly call `DTRSM` from LAPACK twice, which is the routine that actually does the forward-backward subs.

3. Write a pure-nim FBS proc(s) equivalent to `DTRSM`. A naive implementation seems rather straightforward, but I'm not sure if `DTRSM` has additional optimization that would involve more complex implementation and have significant benefits. Some investigation needed here.

4. Don't use `lu_permuted` at all, and wrap `DGESV` directly.

Comments?

**Comment by mratsim** [comment]
> _Somewhat sidetracking: any reason why the LAPACK LU result is duplicated in two tensors in lu_permuted? It seems like an easy memory optimization to avoid this duplication (each matrix is half zeros). Scipy's wrapper to DGETRF, scipy.linalg.lu_factor, returns a single array lu as the wrapped function does._

I approximately follow the high-level `scipy.lu` not `scipy.lu_factor`: https://docs.scipy.org/doc/scipy-1.3.0/reference/generated/scipy.linalg.lu.html?highlight=lu#scipy.linalg.lu

For solving equation via LU, I would call directly the underlying getrf wrapper https://github.com/mratsim/Arraymancer/blob/7fb7e9f1b62691221247186149edbc07402cffc1/src/linear_algebra/helpers/decomposition_lapack.nim#L294-L318
and then pass it to a getrs wrapper.

I don't expose those publicly because Arraymancer exposes already a lot of methods and the low-level ones should be done in a low-level library such as [Laser](https://github.com/numforge/laser).

While Laser is in development, those low-level functions can be used privately within Arraymancer and I compose them extensively in my randomized SVD implementation and do enjoy the memory and compute reduction offered by packing triangular matrices and in-place modification.

I do implement even slightly different procs without reusing the public ones when it makes sense from a compute/memory point of view: https://github.com/mratsim/Arraymancer/blob/7fb7e9f1b62691221247186149edbc07402cffc1/src/linear_algebra/decomposition_rand.nim#L15-L46

LU solving is another such case

**Comment by auxym** [comment]
Thanks for the detailed answer.

Where do you see Arraymancer on the low/high level spectrum? Right now it seems to implement both "low level" numpy/blas type stuff (Tensor type, basic arithmetic and ufuncs) and higher level functionality (linear algebra like LAPACK and scipy.linalg as well as NN/ML stuff).

Do you think a high-level `solve` function, very similar to `scipy.linalg.solve`, would fit in Arraymancer's public API? I wouldn't mind working on a PR (like scipy it would be a wrapper around LAPACK's `gesv`, `sysv`, `hesv` and `posv`).

Or should that functionality simply be in a lower level (laser?) lib?

**Comment by mratsim** [comment]
I consider both numpy and scipy to be mostly high-level except the raw wrappers for Lapack.

For me, low-level is when you need to deal with pointer + length or memory layout (row-major/col-major, ...) and that should be for laser.

Solve would fit with the public API. ``gesv`` and friends should not be public though (and ultimately moved to Laser which would have those public).

**Comment by mratsim** [comment]
implemented in #404
