### ISSUE TITLE
Is there a roadmap

### ISSUE THREAD

**Issue by clive-g-brown** [mratsim/Arraymancer#455]
to get this working on OpenCL/Metal or equivalents?

**Comment by mratsim** [comment]
OpenCL is working.

You can run `nimble test_opencl`

However there is no autodetection of OpenCL device to pick a Nvidia/AMD GPU among devices (among Intel/AMD CPU or FPGA) (https://github.com/mratsim/Arraymancer/issues/186).

Also the support is significantly less developed than for CPU or Cuda.

No plan to make it run on Metal because it doesn't seem like compute is a priority for Apple.

Vulkan Compute, maybe, when there are tutorials explaining how to do a simple Matrix a*X+Y (AXPY, the hello world of linear algebra).

That said, further development on GPU is very time-consuming, hence my plan to write a linear algebra compiler in Laser similar to Halide (#347) with a LLVM IR backend which will bring CPU, Cuda, OpenCL, Vulkan, Metal, DX12 architecture targets "for free".


Are there specific features or functions you are interested in?

**Comment by clive-g-brown** [comment]
Thats helpful. I wish you every success.
Maybe im doing something wrong, I get the same compile error on Win and OSX - possibly not finding the OpenCL headers. I'll try again.
The feature im interested in is to avoid python AND use the AMD GPUs on Mac and/or windows without writing low level stuff AND be able to ship low-dependency binaries. It's not easy.

**Comment by mratsim** [comment]
GPU computing on Mac is a dead-end. Apple deprecated OpenCL in Catalina and Metal Performance Shader cannot replace them.
Also Apple wants to control graphics API on their platform and does not seem to help AMD with getting ROCm working which is a much more compelling target (https://github.com/RadeonOpenCompute/ROCm/issues/262, https://github.com/RadeonOpenCompute/ROCm/issues/997), I suppose to drive everyone to Metal.

Adding ROCm support shouldn't be too hard since it follows CUDA API so closely (see https://github.com/mratsim/Arraymancer/issues/33) but I don't have an AMD GPU and so I can't test and make sure of the implementation details.

**Comment by clive-g-brown** [comment]
that's right however I seem to have it working on Catalina (happy) : 
 
./tests_opencl 

[Suite] OpenCL init
  [OK] .opencl and .cpu conversion
  [OK] zeros_like and ones_like

[Suite] OpenCL BLAS operations (Basic Linear Algebra Subprograms)
  [OK] GEMM - General Matrix to Matrix Multiplication
  [OK] GEMM - Bounds checking
  [OK] GEMV - General Matrix to Vector Multiplication - float32
  [OK] GEMV - General Matrix to Vector Multiplication - float64
  [OK] Matrix and vector addition
  [OK] Matrix and vector substraction
  [OK] Scalar/dot product
  [OK] Matrix and Vector in-place addition
  [OK] Matrix and Vector in-place substraction
  [OK] Matrix and vector addition
  [OK] Matrix and vector substraction

[Suite] OpenCL: Shapeshifting - broadcasting and non linear algebra elementwise operations
  [OK] Tensor element-wise multiplication (Hadamard product) and division
  [OK] Implicit tensor-tensor broadcasting - basic operations +., -., *., ./, .^
