### ISSUE TITLE
Incorrect Result: Mutation with a tensor or tensor slice

### ISSUE THREAD

**Issue by general-rishkin** [mratsim/Arraymancer#506]
![image](https://user-images.githubusercontent.com/72015476/115215836-ce1a5600-a0fb-11eb-9b3d-b5040d6b6d90.png)

Result:
![image](https://user-images.githubusercontent.com/72015476/115215915-e4c0ad00-a0fb-11eb-9f85-1301d5b25624.png)

The result should be: 
![image](https://user-images.githubusercontent.com/72015476/115216577-89db8580-a0fc-11eb-84b3-f03c600f75c8.png)

**Comment by eagledot** [comment]
Hey,
I think code ``foo[^2.. 1,2 .. 4] = foo[^1..^2|-1, 4..2|-1]`` would overwrite the values of ``2nd last row's last 3 columns`` with values from ``last row's last 3 columns in reverse order`` hence,2nd last row would become ``9765625 1953125 390625`` which is the expected value for ``2nd last row``. Now the code is supposed to overwrite  the values  of ``last row's last 3 columns`` with ``2nd last row's last 3 columns in reverse order`` which are expected to be ``1048576 262144 65536``,but we would have already overwritten values of ``2nd last row's last 3 columns``  with values ``9765625  1953125 390625`` and hence in reverse  it would be overwritten as ``390625 1953125 9765625`` .

I think Code mutation logic is working correctly ,the problem here lies in the values we are trying to mutate with values that could have been overwritten and it would almost always lead to unexpected results.

Above  explanation holds only  for single threaded mutation implementation and one may get unexpected and undeterministic results with multi threaded mutation implementation.The above code for showing mutation implementation may not be the best example.
That said @mratsim would be able to take a  better look or may be update example at [https://mratsim.github.io/Arraymancer/tuto.slicing.html](https://mratsim.github.io/Arraymancer/tuto.slicing.html)

**Comment by Vindaar** [comment]
I agree with @eagledot's explanation. 

This is a rather tricky case and it comes down to expectations of what slice mutation is actually supposed to do. Should it actually act on the original memory? Or should it create a temporary clone to use? In my opinion it should do the former. Mutation after all is often used for efficiency reasons and making a clone hampers that.

To expand on eagledot's example with code. Essentially the slicing operation does the following two successive slices:
```nim
# first let's print the LHS we write to
echo foo[^2..^1, 2..4]
# Tensor[system.int] of shape [2, 3]" on backend "Cpu"
# |65536  262144  1048576|
# |390625 1953125 9765625|

# now print the RHS we read from
echo foo[^1..^2|-1, 4..2|-1]

# Tensor[system.int] of shape [2, 3]" on backend "Cpu"
# |9765625        1953125 390625|
# |1048576        262144  65536|

# this means we first perform this:
foo[^2, 2..4] = foo[^1, 4..2|-1]
echo foo
# Tensor[system.int] of shape [5, 5]" on backend "Cpu"
# |1      1       1       1       1|
# |64     128     256     512     1024|
# |729    2187    6561    19683   59049|
# |4096   16384   9765625 1953125 390625|
# |15625  78125   390625  1953125 9765625|


# and then the following. At this step (compare output
foo[^1, 2..4] = foo[^2, 4..2|-1]
echo foo
# Tensor[system.int] of shape [5, 5]" on backend "Cpu"
# |1      1       1       1       1|
# |64     128     256     512     1024|
# |729    2187    6561    19683   59049|
# |4096   16384   9765625 1953125 390625|
# |15625  78125   390625  1953125 9765625|
```

So this is indeed expected behavior under the assumption of actual mutation.

Though to be fair, the tutorial on slicing *does* show the same behavior as in the OP. So this makes me wonder what @mratsim's intention for this was supposed to be.
Also it would be great if someone could compare with what numpy does for a similar slicing mutation.
